project:
  type: website
  
lang: es 
language: es.yml

website:
  title: "IMPACTO"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - intro.qmd
      - first_work.qmd
      - impact.qmd

bibliography: references.bib
csl: apanoa.csl

format:
  html:
    theme: earth.scss
    css: styles.css