---
title: "Encuesta de Impacto"
author: "Oswaldo Navarrete Carreño"
format: revealjs
---

```{r include=FALSE}
library(agricolae)
library(tidyverse)
library(writexl)
library(readxl)
library(jtools)
library(plotly)
library(kableExtra)

orange_earth <- "#f37321"

green_earth <- "#008C99"

datos <- read_excel("datos/data_final.xlsx")

gender <- datos |>
  group_by(Gender) |> 
  summarise(
    N = n(), 
    Porcentaje = round(100*N/nrow(datos),2)
  )

gender_country <- datos |>
  group_by(Gender, Origin_Country) |> 
  summarise(
    N = n(), 
    Porcentaje = round(100*N/nrow(datos),2)
  ) |>
  ungroup()
```

## Generalidades

- La encuesta fue aplicada a `r nrow(datos)` personas. 
- `r gender[1,2]` del total, es decir un `r gender[1,3]`% corresponden al género femenino y un `r gender[2,3]`% al género masculino. 

## Encuestados por país

```{r}
#| label: fig-country
#| fig-cap: "Distribución de los participantes por país"
#| echo: false

country <- datos |>
  group_by(Origin_Country) |> 
  summarise(
    N = n(), 
    Porcentaje = round(100*N/nrow(datos),2)
  )

g2 <- country |>
  mutate(Origin_Country = fct_reorder(Origin_Country, N)) |>
  ggplot( aes(x = Origin_Country, y = N)) +
  geom_bar(stat = "identity", fill = orange_earth) +
  coord_flip() + 
  theme_apa() +
  labs(
    x = "País", y = "Frecuencia"
  )
ggplotly(g2)

```

## Encuestados por país y por género

```{r}
#| label: fig-countrygdr
#| fig-cap: "Distribución de los participantes por país y por género"
#| echo: false

g1 <- gender_country |>
  mutate(Origin_Country = fct_reorder(Origin_Country, Porcentaje)) |>
  ggplot(aes(fill=Gender, y=Porcentaje, x=Origin_Country)) + 
  geom_bar(position="stack", stat="identity" ) +
  labs(x = "País de Origen", y = "Porcentaje") +
  scale_fill_discrete(name = "Género") +
  coord_flip() +
  theme_apa() 

ggplotly(g1) |> layout(legend = list(x = 0.70, y = 0.10))
```
